store: skip template copy with layer in different store
do not attempt to create a layer using a TemplateLayer if the source
layer is in a different store, since the lookup for the source layer
would fail in the layers store.

The reproducer for the error:

Error: error creating container storage: error creating an ID-mapped copy of layer "4fc242d58285699eca05db3cc7c7122a2b8e014d9481f323bd9277baacfa0628": layer not known

Closes: https://github.com/containers/storage/issues/1232

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>